var ACGSiteScriptsFCNS={cambiaFondoMsg:function(a,b,c,d,e){$("#"+a+" .ui-messages-info").css("color",b);$("#"+a+" .ui-messages-info").css("border-color",d);$("#"+a+" .ui-messages-info").css("background-color",c);$("#"+a+" .ui-messages-info-icon").attr("style","background: url("+e+".xhtml) no-repeat !important;");$("#"+a+" .ui-messages-info-icon").addClass("no-after");$("#"+a+" .ui-messages-info ui-corner-all").addClass("ui-messages");$("#"+a+" .ui-messages-info ui-corner-all").removeClass("ui-messages-error");
$("#"+a+" .ui-messages-error").css("color",b);$("#"+a+" .ui-messages-error").css("border-color",d);$("#"+a+" .ui-messages-error").css("background-color",c);$("#"+a+" .ui-messages-error-icon").attr("style","background: url("+e+".xhtml) no-repeat !important;");$("#"+a+" .ui-messages-error-icon").addClass("no-after");$("#"+a+" .ui-messages-error ui-corner-all").addClass("ui-messages");$("#"+a+" .ui-messages-error ui-corner-all").removeClass("ui-messages-error");$("#"+a+" .ui-messages-warn").css("color",
b);$("#"+a+" .ui-messages-warn").css("border-color",d);$("#"+a+" .ui-messages-warn").css("background-color",c);$("#"+a+" .ui-messages-warn-icon").attr("style","background: url("+e+".xhtml) no-repeat !important;");$("#"+a+" .ui-messages-warn-icon").addClass("no-after");$("#"+a+" .ui-messages-warn ui-corner-all").addClass("ui-messages");$("#"+a+" .ui-messages-warn ui-corner-all").removeClass("ui-messages-error");$("#"+a+" .ui-messages-fatal").css("color",b);$("#"+a+" .ui-messages-fatal").css("border-color",
d);$("#"+a+" .ui-messages-fatal").css("background-color",c);$("#"+a+" .ui-messages-fatal-icon").attr("style","background: url("+e+".xhtml) no-repeat !important;");$("#"+a+" .ui-messages-fatal-icon").addClass("no-after");$("#"+a+" .ui-messages-error ui-corner-all").addClass("ui-messages");$("#"+a+" .ui-messages-error ui-corner-all").removeClass("ui-messages-error")},productoResize:function(){if("undefined"!==typeof $("#outputPanelProductos")){var a=$("#bodyPpal").height()-(0<$("#panelSelUsr").length?
$("#panelSelUsr").outerHeight(!0):0)-(0<$("#mnuIconos").length?$("#mnuIconos").outerHeight(!0):0)-((0<$("#panelProductos_header").length?parseFloat($("#panelProductos_header").outerHeight(!0)):0)+(0<$("#panelProductos").length?parseFloat($("#panelProductos").css("padding-top").replace("px",""))+parseFloat($("#panelProductos").css("padding-bottom").replace("px",""))+parseFloat($("#panelProductos").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos").css("border-bottom-width").replace("px",
"")):0)+(0<$("#panelProductos_content").length?parseFloat($("#panelProductos_content").css("padding-top").replace("px",""))+parseFloat($("#panelProductos_content").css("padding-bottom").replace("px",""))+parseFloat($("#panelProductos_content").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos_content").css("border-bottom-width").replace("px","")):0));$("#outputPanelProductos").height(a);ACGSiteScriptsFCNS.resultadoResize()}},puntoVentaResize:function(){var a=window.innerHeight;
1024>window.innerWidth&&(a-=17);a-=$("#headerPpal").outerHeight(!0);a-=$("#footerPpal").outerHeight(!0);$("#bodyPpal").height(a-4);ACGSiteScriptsFCNS.productoResize()},monitorPVResize:function(){$("#headerPpal").outerHeight(!0);$("#footerPpal").outerHeight(!0);0<$("#panelProductos_header").length&&parseFloat($("#panelProductos_header").outerHeight(!0));0<$("#panelProductos").length&&(parseFloat($("#panelProductos").css("padding-top").replace("px","")),parseFloat($("#panelProductos").css("padding-bottom").replace("px",
"")),parseFloat($("#panelProductos").css("border-top-width").replace("px","")),parseFloat($("#panelProductos").css("border-bottom-width").replace("px","")));0<$("#panelProductos_content").length&&(parseFloat($("#panelProductos_content").css("padding-top").replace("px","")),parseFloat($("#panelProductos_content").css("padding-bottom").replace("px","")),parseFloat($("#panelProductos_content").css("border-top-width").replace("px","")),parseFloat($("#panelProductos_content").css("border-bottom-width").replace("px",
"")));if(0<$("#tablaMonitorTRXSPV .ui-datatable-scrollable-body").length){var a=$("#outputPanelProductos").height()-($("#tablaMonitorTRXSPV .ui-datatable-header").outerHeight(!0)+$("#tablaMonitorTRXSPV .ui-datatable-scrollable-header").outerHeight(!0)+$("#tablaMonitorTRXSPV .ui-datatable-scrollable-footer-box").outerHeight(!0)+$("#tablaMonitorTRXSPV_paginator_bottom").outerHeight(!0)+15);$("#tablaMonitorTRXSPV .ui-datatable-scrollable-body").attr("style","max-height: "+a+"px;");$("#tablaMonitorTRXSPV .ui-datatable-scrollable-body").attr("style",
"height: "+a+"px;")}},cierraPanelProducto:function(){0<$("#panelProductos").length&&PF("panelProductosWV").close()},resultadoResize:function(){},deshabilitaSeleccionMenu:function(){$("#admTabMenu .ui-state-active").removeClass("ui-state-active")},refreshMonPV:function(){0<$("#panelGroupMonPV").length&&refreshMonProductosOnlinePV()}};var AdministracionFCNS={cambiaFondoMsg:function(a,b,c,d,e){$("#"+a+" .ui-messages-info").css("color",b);$("#"+a+" .ui-messages-info").css("border-color",d);$("#"+a+" .ui-messages-info").css("background-color",c);$("#"+a+" .ui-messages-info-icon").attr("style","background: url("+e+".xhtml) no-repeat !important;");$("#"+a+" .ui-messages-info-icon").addClass("no-after");$("#"+a+" .ui-messages-info ui-corner-all").addClass("ui-messages");$("#"+a+" .ui-messages-info ui-corner-all").removeClass("ui-messages-error");
$("#"+a+" .ui-messages-error").css("color",b);$("#"+a+" .ui-messages-error").css("border-color",d);$("#"+a+" .ui-messages-error").css("background-color",c);$("#"+a+" .ui-messages-error-icon").attr("style","background: url("+e+".xhtml) no-repeat !important;");$("#"+a+" .ui-messages-error-icon").addClass("no-after");$("#"+a+" .ui-messages-error ui-corner-all").addClass("ui-messages");$("#"+a+" .ui-messages-error ui-corner-all").removeClass("ui-messages-error");$("#"+a+" .ui-messages-warn").css("color",
b);$("#"+a+" .ui-messages-warn").css("border-color",d);$("#"+a+" .ui-messages-warn").css("background-color",c);$("#"+a+" .ui-messages-warn-icon").attr("style","background: url("+e+".xhtml) no-repeat !important;");$("#"+a+" .ui-messages-warn-icon").addClass("no-after");$("#"+a+" .ui-messages-warn ui-corner-all").addClass("ui-messages");$("#"+a+" .ui-messages-warn ui-corner-all").removeClass("ui-messages-error");$("#"+a+" .ui-messages-fatal").css("color",b);$("#"+a+" .ui-messages-fatal").css("border-color",
d);$("#"+a+" .ui-messages-fatal").css("background-color",c);$("#"+a+" .ui-messages-fatal-icon").attr("style","background: url("+e+".xhtml) no-repeat !important;");$("#"+a+" .ui-messages-fatal-icon").addClass("no-after");$("#"+a+" .ui-messages-error ui-corner-all").addClass("ui-messages");$("#"+a+" .ui-messages-error ui-corner-all").removeClass("ui-messages-error")},productoResize:function(){if("undefined"!==typeof $("#outputPanelProductos")){var a=$("#bodyPpal").height()-(0<$("#panelSelUsr").length?
$("#panelSelUsr").outerHeight(!0):0)-(0<$("#mnuIconos").length?$("#mnuIconos").outerHeight(!0):0)-((0<$("#panelProductos_header").length?parseFloat($("#panelProductos_header").outerHeight(!0)):0)+(0<$("#panelProductos").length?parseFloat($("#panelProductos").css("padding-top").replace("px",""))+parseFloat($("#panelProductos").css("padding-bottom").replace("px",""))+parseFloat($("#panelProductos").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos").css("border-bottom-width").replace("px",
"")):0)+(0<$("#panelProductos_content").length?parseFloat($("#panelProductos_content").css("padding-top").replace("px",""))+parseFloat($("#panelProductos_content").css("padding-bottom").replace("px",""))+parseFloat($("#panelProductos_content").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos_content").css("border-bottom-width").replace("px","")):0));$("#outputPanelProductos").height(a);AdministracionFCNS.resultadoResize()}},cierraPanelProducto:function(){0<$("#panelProductos").length&&
PF("panelProductosWV").close()},resultadoResize:function(){}};window.addEventListener("resize",ACGSiteScriptsFCNS.resultadoResize);$(document).ready(function(){ACGSiteScriptsFCNS.resultadoResize()});AdministracionFCNS.deshabilitaSeleccionMenu=function(){$("#admTabMenu .ui-state-active").removeClass("ui-state-active")};var AdministracionUsuariosFCNS={};
ACGSiteScriptsFCNS.resultadoResize=function(){0<$("#usuariosAdminDT").length&&(theHeight=$("#outputPanelProductos").height(),theHeight-=15,theHeight-=$("#botoneraUsuario").height(),$("#usuariosAdminDT").css("maxHeight",theHeight+"px"),$("#usuariosAdminDT").height(theHeight),theHeight-=$("#usuariosAdminDT .ui-widget-header.ui-datatable-scrollable-header").height(),$("#usuariosAdminDT .ui-datatable-scrollable-body").css("height",theHeight+"px"),PF("usuariosAdminDTWV").scrollBody.scrollTop(1),PF("usuariosAdminDTWV").allLoadedLiveScroll=
!1,PF("usuariosAdminDTWV").scrollOffset=0,PF("usuariosAdminDTWV").clearScrollState(),PF("usuariosAdminDTWV").adjustScrollHeight())};$.ajaxSetup({headers:{"X-CSRF-TOKEN":$('META[NAME="_csrf"]').attr("content")}});var ArbolFCNS={ocultar:function(a){for(ind=0;6>=ind;ind++)PrimeFaces.widgets["dtWidgetVar"+ind]&&a!="dtWidgetVar"+ind&&PF("dtWidgetVar"+ind).unselectAllRows()},arbolResize:function(a){var b=window.innerHeight;$("#bodyPpal").width();1024>window.innerWidth&&(b-=17);b-=$("#headerPpal").outerHeight(!0);b-=$("#footerPpal").outerHeight(!0);b-=parseFloat($("#bodyPpal").css("padding-top").replace("px",""));b-=parseFloat($("#bodyPpal").css("padding-bottom").replace("px",""));b-=parseFloat($("#bodyPpal").css("border-top").replace("px",
""));b-=parseFloat($("#bodyPpal").css("border-bottom").replace("px",""));$("#bodyPpal").height(b);b-=$("#panelSelUsr_header").outerHeight(!0);b-=$("#panelSelUsr_content").css("borderBottomWidth").replace("px","");b-=parseFloat($("#panelSelUsr_content").css("padding-top").replace("px",""));b-=parseFloat($("#panelSelUsr_content").css("padding-bottom").replace("px",""));$("#contSelUsr").css("maxHeight",b+"px");$("#contSelUsr").height(b);$("#contenedorDataArbol").css("maxHeight",b+"px");$("#contenedorDataArbol").height(b);
if(0<$("#gridContArbol").length){b-=parseFloat($("#contenedorDataArbol").css("borderTopWidth").replace("px",""));b-=parseFloat($("#contenedorDataArbol").css("borderBottomWidth").replace("px",""));b-=parseFloat($("#contenedorDataArbol").css("padding-top").replace("px",""));b-=parseFloat($("#contenedorDataArbol").css("padding-bottom").replace("px",""));$("#gridContArbol").css("maxHeight",b+"px");$("#gridContArbol").height(b);b-=10;$("#arbolNivel1").css("maxHeight",b+"px");$("#arbolNivel1").height(b);
$("#arbolNivel2").css("maxHeight",b+"px");$("#arbolNivel2").height(b);$("#arbolNivel3").css("maxHeight",b+"px");$("#arbolNivel3").height(b);$("#arbolNivel4").css("maxHeight",b+"px");$("#arbolNivel4").height(b);$("#arbolNivel5").css("maxHeight",b+"px");$("#arbolNivel5").height(b);0==a&&(PF("dtWidgetVar1").scrollBody.scrollTop(1),PF("dtWidgetVar1").allLoadedLiveScroll=!1,PF("dtWidgetVar1").scrollOffset=0,PF("dtWidgetVar1").clearScrollState(),PF("dtWidgetVar1").adjustScrollHeight());if(0==a||1>=a)PF("dtWidgetVar2").scrollBody.scrollTop(1),
PF("dtWidgetVar2").allLoadedLiveScroll=!1,PF("dtWidgetVar2").scrollOffset=0,PF("dtWidgetVar2").clearScrollState(),PF("dtWidgetVar2").adjustScrollHeight();if(0==a||2>=a)PF("dtWidgetVar3").scrollBody.scrollTop(1),PF("dtWidgetVar3").allLoadedLiveScroll=!1,PF("dtWidgetVar3").scrollOffset=0,PF("dtWidgetVar3").clearScrollState(),PF("dtWidgetVar3").adjustScrollHeight();if(0==a||3>=a)PF("dtWidgetVar4").scrollBody.scrollTop(1),PF("dtWidgetVar4").allLoadedLiveScroll=!1,PF("dtWidgetVar4").scrollOffset=0,PF("dtWidgetVar4").clearScrollState(),
PF("dtWidgetVar4").adjustScrollHeight();if(0==a||4>=a)PF("dtWidgetVar5").scrollBody.scrollTop(1),PF("dtWidgetVar5").allLoadedLiveScroll=!1,PF("dtWidgetVar5").scrollOffset=0,PF("dtWidgetVar5").clearScrollState(),PF("dtWidgetVar5").adjustScrollHeight()}else $("#resuBusCliDT").css("maxHeight",b+"px"),$("#resuBusCliDT").height(b),PF("resuBusCliDTWV").scrollBody.scrollTop(1),PF("resuBusCliDTWV").allLoadedLiveScroll=!1,PF("resuBusCliDTWV").scrollOffset=0,PF("resuBusCliDTWV").clearScrollState(),PF("resuBusCliDTWV").adjustScrollHeight();
"undefined"!==typeof AdministracionFCNS&&AdministracionFCNS.productoResize()},clearFilters:function(a){var b,c,d,e,f;0==a&&(b=PF("dtWidgetVar1"),void 0!==b&&b.thead.find("> tr > th.ui-filter-column > .ui-column-customfilter > .ui-column-acg-filter").val(""));if(0==a||1>=a)c=PF("dtWidgetVar2"),void 0!==c&&c.thead.find("> tr > th.ui-filter-column > .ui-column-customfilter > .ui-column-acg-filter").val("");if(0==a||2>=a)d=PF("dtWidgetVar3"),void 0!==d&&d.thead.find("> tr > th.ui-filter-column > .ui-column-customfilter > .ui-column-acg-filter").val("");
if(0==a||3>=a)e=PF("dtWidgetVar4"),void 0!==e&&e.thead.find("> tr > th.ui-filter-column > .ui-column-customfilter > .ui-column-acg-filter").val("");if(0==a||4>=a)f=PF("dtWidgetVar5"),void 0!==f&&f.thead.find("> tr > th.ui-filter-column > .ui-column-customfilter > .ui-column-acg-filter").val("");PF("blockPanelGral").show();(0==a||5==a)&&void 0!==f&&f.filter();(0==a||4==a)&&void 0!==e&&e.filter();(0==a||3==a)&&void 0!==d&&d.filter();(0==a||2==a)&&void 0!==c&&c.filter();(0==a||1==a)&&void 0!==b&&b.filter();
PF("blockPanelGral").hide()},unselectAllRows:function(){for(ind=0;6>=ind;ind++)PrimeFaces.widgets["dtWidgetVar"+ind]&&PF("dtWidgetVar"+ind).unselectAllRows()}};$(window).on("resize",ArbolFCNS.arbolResize);$(document).ready(function(){ArbolFCNS.arbolResize(0)});document.onkeydown=keyboardDown;document.onkeyup=keyboardUp;document.oncontextmenu=function(a){var b=Object({keyCode:93});stopEvent(a);keyboardUp(b)};function stopEvent(a){void 0!=a.preventDefault&&a.preventDefault();void 0!=a.stopPropagation&&a.stopPropagation()}function keyboardDown(a){if(!window.event&&!a)return!0}function keyboardUp(a){if(!window.event&&!a)return!0};PrimeFaces.locales.es={closeText:"Cerrar",prevText:"Anterior",nextText:"Siguiente",monthNames:"Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre".split(","),monthNamesShort:"Ene,Feb,Mar,Abr,May,Jun,Jul,Ago,Sep,Oct,Nov,Dic".split(","),dayNames:"Domingo,Lunes,Martes,Mi\u00e9rcoles,Jueves,Viernes,S\u00e1bado".split(","),dayNamesShort:"Dom,Lun,Mar,Mie,Jue,Vie,Sab".split(","),dayNamesMin:"D,L,M,X,J,V,S".split(","),weekHeader:"Semana",firstDay:1,isRTL:!1,showMonthAfterYear:!1,
yearSuffix:"",timeOnlyTitle:"S\u00f3lo hora",timeText:"Tiempo",hourText:"Hora",minuteText:"Minuto",secondText:"Segundo",currentText:"Fecha actual",ampm:!1,month:"Mes",week:"Semana",day:"D\u00eda",allDayText:"Todo el d\u00eda",today:"Hoy",clear:"Borrar"};var gcsiScriptsFCNS={handleKeyDown:function(a){"F2"==a.key?$("#btnCONTINUAR").click():"F4"==a.key?$("#btnLimpiarLista").click():"F7"==a.key?$("#btnManual").click():"F8"==a.key?$("#btnBarra").click():"F9"==a.key?$("#btnConfirmarPagos").click():"F10"==a.key&&$("#btnMPConfirmarPagos").click()}};
ACGSiteScriptsFCNS.resultadoResize=function(){$("#contenedorTabla").height($("#outputPanelProductos").height()-(0<$("#msgsProductos").length?$("#msgsProductos").outerHeight(!0):0)-15);$("#contenedorMenu").height($("#contenedorTabla").height()-$("#contenedorEstado").height()-8)};
gcsiScriptsFCNS.procesarSinFacGIRE=function(){var a=[];$(".camposGIRE").each(function(b,d){var e={};e.etiqueta=$(".etiquetaGIRE",d).text();e.nombre=$(".nombreCampoGIRE",d).attr("valor");e.tipo=$(".nombreCampoGIRE",d).attr("tipo");e.valor="COMBO_BOX_ESTATICO"==$(".nombreCampoGIRE",d).attr("tipo")||"COMBO_BOX_DINAMICO"==$(".nombreCampoGIRE",d).attr("tipo")?$(".valorCampoGIRE option:selected",d).val():$(".valorCampoGIRE",d).val();a.push(e)});var b=JSON.stringify(a);callScript([{name:"parametro",value:"cob"},
{name:"tipo",value:"proccobman"},{name:"valor",value:b},{name:"texto",value:""}])};document.addEventListener("keydown",gcsiScriptsFCNS.handleKeyDown);function Popup(a){var b=window.open("","my div","height=500,width=520,left=100,top=100,resizable=yes,scrollbars=yes,toolbar=no,status=no");b.document.write("<html><head><title>Ticket</title>");b.document.write('<link rel="stylesheet" href="styles/ticket-styles.css" type="text/css" />');b.document.write("</head><body >");b.document.write(a);b.document.write("</body></html>");b.document.close();myDelay=setInterval(function(){"complete"==b.document.readyState&&(clearInterval(myDelay),b.focus(),b.print(),
b.close())},10);return!0};function swapClass(a,b){a.className=b}function isUndefined(a){return void 0==a}function checkAll(a){for(var b=0;b<a.elements.length;b++){var c=a.elements[b];"allbox"!=c.name&&0==c.type.indexOf("checkbox")&&(c.checked=a.allbox.checked)}}
function clearForm(a){for(var b=0;b<a.length;b++){var c=a.elements[b];if(0==c.type.indexOf("text")||0==c.type.indexOf("password"))c.value="";else if(0==c.type.indexOf("radio"))c.checked=!1;else if(0==c.type.indexOf("checkbox"))c.checked=!1;else if(0==c.type.indexOf("select")){for(var d=0;d<c.length;d++)c.options[d].selected=!1;c.options[0].selected=!0}}}
function getFormAsString(a){for(var b="",c=0;c<a.length;c++){var d=a.elements[c];if(0==d.type.indexOf("checkbox")||0==d.type.indexOf("radio"))d.checked&&(b+=d.name+"="+escape(d.value)+"&");else if(0==d.type.indexOf("select"))for(var e=0;e<d.length;e++)d.options[e].selected&&(b+=d.name+"="+escape(d.value)+"&");else b+=d.name+"="+escape(d.value)+"&"}return b}
function toggleForm(a,b){for(var c=0;c<a.length;c++)if(0==a.elements[c].type.indexOf("select")||0==a.elements[c].type.indexOf("checkbox"))a.elements[c].style.visibility=b?"visible":"hidden"}function opt(a,b,c){this.txt=a;this.val=b;this.sel=c}
function move(a,b){var c=a.options.length;index=a.selectedIndex;if(-1==index||1==b&&index==c-1||-1==b&&0==index)return!1;var b=index+b,d=[];for(i=0;i<c;i++)d[i]=new opt(a.options[i].text,a.options[i].value,a.options[i].selected);tempOpt=d[b];d[b]=d[index];d[index]=tempOpt;for(i=a.options.length=0;i<d.length;i++)a.options[i]=new Option(d[i].txt,d[i].val),a.options[i].selected=d[i].sel;a.focus()}
function selectAll(a){a=document.getElementById(a);len=a.length;if(0!=len)for(i=0;i<len;i++)a.options[i].selected=!0}function toggleChoice(a){a=document.getElementById(a);a.checked=a.checked?!1:!0}function toggleRadio(a,b){document.getElementsByName(a)[b].checked=!0}function openWindow(a,b,c){winName=window.open(a,b,c);winName.focus()}
function openSearch(a,b){var c=parseInt(screen.availWidth),d=parseInt(screen.availHeight);openWindow(a,b,"width="+c+",height="+d+",left=0,top=0,toolbar,scrollbars,resizable,status=yes")}function setCookie(a,b,c,d,e,f){document.cookie=a+"="+escape(b)+(c?"; expires="+c.toUTCString():"")+(d?"; path="+d:"")+(e?"; domain="+e:"")+(f?"; secure":"")}
function getCookie(a){var a=a+"=",b=document.cookie.indexOf(a);if(-1==b)return null;var c=document.cookie.indexOf(";",b+a.length);-1==c&&(c=document.cookie.length);a=document.cookie.substring(b+a.length,c);return unescape(a)}function deleteCookie(a,b,c){getCookie(a)&&(document.cookie=a+"="+(b?"; path="+b:"")+(c?"; domain="+c:"")+"; expires=Thu, 01-Jan-70 00:00:01 GMT")}String.prototype.trim=function(){return this.replace(/^\s*(\S*(\s+\S+)*)\s*$/,"$1")};
function validateRequired(a){var b=!0,c=null,d=0,e=[];oRequired=new required;for(x in oRequired)if(("text"==a[oRequired[x][0]].type||"textarea"==a[oRequired[x][0]].type||"select-one"==a[oRequired[x][0]].type||"radio"==a[oRequired[x][0]].type||"password"==a[oRequired[x][0]].type)&&""==a[oRequired[x][0]].value)0==d&&(c=a[oRequired[x][0]]),e[d++]=oRequired[x][1],b=!1;0<e.length&&(c.focus(),alert(e.join("\n")));return b}
function createFormElement(a,b,c,d,e,f){a=document.createElement(a);a.setAttribute("name",c);a.setAttribute("type",b);a.setAttribute("id",d);a.setAttribute("value",e);f.appendChild(a)}function confirmDelete(a){return(ans=confirm("Are you sure you want to delete this "+a+"?"))?!0:!1}
function highlightTableRows(a){var b=null,c=document.getElementById(a),a=0;c.getElementsByTagName("thead")[0]||(a=1);c=c.getElementsByTagName("tbody")[0].getElementsByTagName("tr");for(i=a;i<c.length;i++)c[i].onmouseover=function(){b=this.className;this.className+=" over"},c[i].onmouseout=function(){this.className=b},c[i].onclick=function(){var a=this.getElementsByTagName("td")[0].getElementsByTagName("a")[0];a.onclick?(call=a.getAttribute("onclick"),0==call.indexOf("return ")&&(call=call.substring(7)),
eval(call)):location.href=a.getAttribute("href");this.style.cursor="wait";return!1}}function highlightFormElements(){addFocusHandlers(document.getElementsByTagName("input"));addFocusHandlers(document.getElementsByTagName("textarea"))}
function addFocusHandlers(a){for(i=0;i<a.length;i++)"button"!=a[i].type&&"submit"!=a[i].type&&"reset"!=a[i].type&&"checkbox"!=a[i].type&&"radio"!=a[i].type&&!a[i].getAttribute("readonly")&&!a[i].getAttribute("disabled")&&(a[i].onfocus=function(){this.style.backgroundColor="#ffd";this.select()},a[i].onmouseover=function(){this.style.backgroundColor="#ffd"},a[i].onblur=function(){this.style.backgroundColor=""},a[i].onmouseout=function(){this.style.backgroundColor=""})}
function radio(a){var b=a.form.elements[a.name];if(!a.checked||!b.length)return a.parentNode.parentNode.className="",!1;for(i=0;i<b.length;i++)b[i]!=a&&(b[i].checked=!1,b[i].parentNode.parentNode.className="");a.parentNode.parentNode.className="over"}
window.onload=function(){highlightFormElements();$("successMessages")&&new Effect.Highlight("successMessages");$("errorMessages")&&new Effect.Highlight("errorMessages");if($("primary-nav"))for(var a=$("primary-nav").getElementsByTagName("li"),b=0;b<a.length;b++)"menubar"==a[b].className&&(a[b].onmouseover=function(){this.className+=" over"},a[b].onmouseout=function(){this.className="menubar"})};window.defaultStatus=document.title;function esMayorIgualHoy(a){var b=getHoy();return a.date<b?!1:!0}
function esMayorHoy(a){var b=getHoy();return a.date<=b?!1:!0}function esMenorIgualHoy(a){var b=getHoy();return a.date>b?!1:!0}function getHoy(){var a=new Date;a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);return a}function Solo_Numerico(a,b){a=a.replace(".","");a=a.replace(",","");Numer="false"==b&&0<a.length&&"0"==a.substr(0,1)?a.substr(1,a.length):a;isNaN(Numer)&&(Numer=0<Numer.length?Numer.substr(0,Numer.length-1):"");return Numer}
function Numerico_Decimal(a){Res="";isNaN(a)?(Numer=parseFloat(a)||0,Res="0"==Numer?"":Numer):Res=a;return Res}function ValNumero(a,b){a.value=Solo_Numerico(a.value,b)}function ValNumeroDecimal(a){a.value=Numerico_Decimal(a.value)}function IsNumeric(a){var b=!0,c;for(i=0;i<a.length&&!0==b;i++)c=a.charAt(i),-1=="0123456789.".indexOf(c)&&(b=!1);return b};function setNext(a,b){13==a&&(0<b.indexOf(":")&&(b=b.replace(":","\\:")),setTimeout(function(){$("#"+b).focus()},1))}function setFocusAndSelectInput(a){0<a.indexOf(":")&&(a=a.replace(":","\\:"));setTimeout(function(){$("#"+a+"_input").focus()},1)}function setFocusAndSelect(a){0<a.indexOf(":")&&(a=a.replace(":","\\:"));setTimeout(function(){$("#"+a).focus()},1)}
function Solo_Numerico(a,b){a=a.replace(".","");a=a.replace(",","");Numer="false"==b&&0<a.length&&"0"==a.substr(0,1)?a.substr(1,a.length):a;isNaN(Numer)&&(Numer=0<Numer.length?Numer.substr(0,Numer.length-1):"");return Numer}function Numerico_Decimal(a){Res="";isNaN(a)?(Numer=parseFloat(a)||0,Res="0"==Numer?"":Numer):Res=a;return Res}function ValNumero(a,b){a.value=Solo_Numerico(a.value,b)}function ValNumeroDecimal(a){a.value=Numerico_Decimal(a.value)};function placeholders2(){$(".placeholder [type=text], .placeholder [type=password], .placeholder [type=email], .placeholder [type=number], .placeholder [type=tel], .placeholder [type=search]").each(function(){if(!$(this).parent().hasClass("ac-placeholder")){$(this).val()&&$(this).addClass("focus");var a=$(this).attr("placeholder");$(this).removeAttr("placeholder").attr("ac-placeholder",a).wrap("<div class='ac-placeholder'></div>").after("<label>"+a+"</label>")}});$(".ac-placeholder input, .ac-placeholder select, .ac-placeholder textarea").focus(function(){$(this).parent().addClass("focus")});
$(".ac-placeholder label").click(function(){$(this).parent().addClass("focus");$(this).prev().focus()});$(".ac-placeholder input, .ac-placeholder select, .ac-placeholder textarea").blur(function(){$(this).val()?$(this).parent().addClass("text"):$(this).parent().removeClass("text");if("tel"==$(this).context.type){var a=/\D+/g;val=$(this).val();val=val.replace(a,"");10<val.length&&(a=/^00/,val=val.replace(a,""),"549"==val.substring(0,3)?a=/^549/:"54"==val.substring(0,2)&&(a=/^54/),val=val.replace(a,
""),a=/^0/,val=val.replace(a,""));12==val.length&&(a=/15/,"15"==val.substring(1,3)?val=val.replace(a,""):"15"==val.substring(2,4)?val=val.replace(a,""):"15"==val.substring(3,5)&&(val=val.replace(a,"")))}$(this).parent().removeClass("focus")})}placeholders2();!function(a){function b(a){var b="",c;for(c in a)a.hasOwnProperty(c)&&(b+=c+":"+a[c]+";");return b}var c=c||{},d=document.querySelectorAll.bind(document),e={duration:500,show:function(a){if(2===a.button)return!1;var c=document.createElement("div");c.className="waves-ripple";this.appendChild(c);var d,g,m,h={top:0,left:0};d=this&&this.ownerDocument;d=(g=d.documentElement,"undefined"!=typeof this.getBoundingClientRect&&(h=this.getBoundingClientRect()),m=null!==d&&d===d.window?d:9===d.nodeType&&d.defaultView,
{top:h.top+m.pageYOffset-g.clientTop,left:h.left+m.pageXOffset-g.clientLeft});g=a.pageY-d.top-45;d=a.pageX-d.left-45;a="scale("+2.5*(this.clientWidth/100)+")";c.setAttribute("data-hold",Date.now());c.setAttribute("data-scale",a);c.setAttribute("data-x",d);c.setAttribute("data-y",g);d={top:g+"px",left:d+"px"};c.className+=" waves-notransition";c.setAttribute("style",b(d));c.className=c.className.replace("waves-notransition","");d["-webkit-transform"]=a;d["-moz-transform"]=a;d["-ms-transform"]=a;d["-o-transform"]=
a;d.transform=a;d.opacity="1";d["-webkit-transition-duration"]=e.duration+"ms";d["-moz-transition-duration"]=e.duration+"ms";d["-o-transition-duration"]=e.duration+"ms";d["transition-duration"]=e.duration+"ms";c.setAttribute("style",b(d))},hide:function(){for(var a=this,c=(1.4*a.clientWidth,null),d=a.children.length,g=0;d>g;g++)-1===a.children[g].className.indexOf("waves-ripple")||(c=a.children[g]);if(!c)return!1;var m=c.getAttribute("data-x"),h=c.getAttribute("data-y"),j=c.getAttribute("data-scale"),
d=500-(Date.now()-Number(c.getAttribute("data-hold")));0>d&&(d=0);setTimeout(function(){c.setAttribute("style",b({top:h+"px",left:m+"px",opacity:"0","-webkit-transition-duration":e.duration+"ms","-moz-transition-duration":e.duration+"ms","-o-transition-duration":e.duration+"ms","transition-duration":e.duration+"ms","-webkit-transform":j,"-moz-transform":j,"-ms-transform":j,"-o-transform":j,transform:j}));setTimeout(function(){try{a.removeChild(c)}catch(b){return!1}},e.duration)},d)},wrapInput:function(a){for(var b=
0;b<a.length;b++){var c=a[b];if("input"===c.tagName.toLowerCase()){var d=c.parentNode;if("i"===d.tagName.toLowerCase()&&-1!==d.className.indexOf("waves-effect"))return!1;var e=document.createElement("i");e.className=c.className+" waves-input-wrapper";var h=c.getAttribute("style"),j="width:"+c.offsetWidth+"px;height:"+c.clientHeight+"px;";h||(h="");e.setAttribute("style",j+h);c.className="waves-button-input";c.removeAttribute("style");d.replaceChild(e,c);e.appendChild(c)}}}};c.displayEffect=function(a){a=
a||{};"duration"in a&&(e.duration=a.duration);e.wrapInput(d(".waves-effect"));Array.prototype.forEach.call(d(".waves-effect"),function(a){a.addEventListener("mousedown",e.show,!1);a.addEventListener("mouseup",e.hide,!1);a.addEventListener("mouseleave",e.hide,!1)})};a.Waves=c}(window);(function(a){a(".input100").each(function(){a(this).on("blur",function(){""!=a(this).val().trim()?a(this).addClass("has-val"):a(this).removeClass("has-val")})});var b=a(".validate-input .input100");a(".validate-form").on("submit",function(){for(var c=!0,d=0;d<b.length;d++){var e;a:{e=b[d];if("email"==a(e).attr("type")||"email"==a(e).attr("name")){if(null==a(e).val().trim().match(/^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{1,5}|[0-9]{1,3})(\]?)$/)){e=
!1;break a}}else if(""==a(e).val().trim()){e=!1;break a}e=void 0}!1==e&&(c=a(b[d]).parent(),a(c).addClass("alert-validate"),c=!1)}return c});a(".validate-form .input100").each(function(){a(this).focus(function(){var b=a(this).parent();a(b).removeClass("alert-validate")})})})(jQuery);/*

 Copyright (c) 2016 Federico Zivolo and contributors

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
*/
(function(a,b){"object"===typeof exports&&"undefined"!==typeof module?module.exports=b(require("popper.js")):"function"===typeof define&&define.amd?define(["popper.js"],b):a.Tooltip=b(a.Popper)})(this,function(a){var a=a&&"default"in a?a["default"]:a,b=function(){function a(b,c){for(var d=0;d<c.length;d++){var e=c[d];e.enumerable=e.enumerable||!1;e.configurable=!0;"value"in e&&(e.writable=!0);Object.defineProperty(b,e.key,e)}}return function(b,c,d){c&&a(b.prototype,c);d&&a(b,d);return b}}(),c=Object.assign||
function(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(a[d]=c[d])}return a},d={container:!1,delay:0,html:!1,placement:"top",title:"",template:'<div class="tooltip" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover focus",offset:0},e=function(){var a=this;this.show=function(){return a._show(a.reference,a.options)};this.hide=function(){return a._hide()};this.dispose=function(){return a._dispose()};
this.toggle=function(){return a._isOpen?a.hide():a.show()};this.arrowSelector=".tooltip-arrow, .tooltip__arrow";this.innerSelector=".tooltip-inner, .tooltip__inner";this._events=[];this._setTooltipNodeEvent=function(b,c,d,e){d=function j(d){var g=d.relatedreference||d.toElement;a._tooltipNode.removeEventListener(b.type,j);c.contains(g)||a._scheduleHide(c,e.delay,e,d)};return a._tooltipNode.contains(b.relatedreference||b.toElement)?(a._tooltipNode.addEventListener(b.type,d),!0):!1}};return function(){function f(a,
b){if(!(this instanceof f))throw new TypeError("Cannot call a class as a function");e.call(this);b=c({},d,b);a.jquery&&(a=a[0]);this.reference=a;this.options=b;var g="string"===typeof b.trigger?b.trigger.split(" ").filter(function(a){return-1!==["click","hover","focus"].indexOf(a)}):[];this._isOpen=!1;this._setEventListeners(a,g,b)}b(f,[{key:"_create",value:function(a,b,c,d){var e=window.document.createElement("div");e.innerHTML=b.trim();b=e.childNodes[0];b.id="tooltip_"+Math.random().toString(36).substr(2,
10);b.setAttribute("aria-hidden","false");e=e.querySelector(this.innerSelector);1===c.nodeType?d&&e.appendChild(c):c&&"[object Function]"===(void 0).call(c)?(a=c.call(a),d?e.innerHTML=a:e.innerText=a):d?e.innerHTML=c:e.innerText=c;return b}},{key:"_show",value:function(b,d){if(this._isOpen)return this;this._isOpen=!0;if(this._tooltipNode)return this._tooltipNode.style.display="",this._tooltipNode.setAttribute("aria-hidden","false"),this.popperInstance.update(),this;var e=b.getAttribute("title")||
d.title;if(!e)return this;e=this._create(b,d.template,e,d.html);b.setAttribute("aria-describedby",e.id);var f=this._findContainer(d.container,b);this._append(e,f);f=c({},d.popperOptions,{placement:d.placement});f.modifiers=c({},f.modifiers,{arrow:{element:this.arrowSelector}});d.boundariesElement&&(f.modifiers.preventOverflow={boundariesElement:d.boundariesElement});this.popperInstance=new a(b,e,f);this._tooltipNode=e;return this}},{key:"_hide",value:function(){if(!this._isOpen)return this;this._isOpen=
!1;this._tooltipNode.style.display="none";this._tooltipNode.setAttribute("aria-hidden","true");return this}},{key:"_dispose",value:function(){var a=this;this._tooltipNode&&(this._hide(),this.popperInstance.destroy(),this._events.forEach(function(b){a.reference.removeEventListener(b.event,b.func)}),this._events=[],this._tooltipNode.parentNode.removeChild(this._tooltipNode),this._tooltipNode=null);return this}},{key:"_findContainer",value:function(a,b){"string"===typeof a?a=window.document.querySelector(a):
!1===a&&(a=b.parentNode);return a}},{key:"_append",value:function(a,b){b.appendChild(a)}},{key:"_setEventListeners",value:function(a,b,c){var d=this,e=[],f=[];b.forEach(function(a){switch(a){case "hover":e.push("mouseenter");f.push("mouseleave");break;case "focus":e.push("focus");f.push("blur");break;case "click":e.push("click"),f.push("click")}});e.forEach(function(b){var e=function(b){!0!==d._isOpen&&(b.usedByTooltip=!0,d._scheduleShow(a,c.delay,c,b))};d._events.push({event:b,func:e});a.addEventListener(b,
e)});f.forEach(function(b){var e=function(b){!0!==b.usedByTooltip&&d._scheduleHide(a,c.delay,c,b)};d._events.push({event:b,func:e});a.addEventListener(b,e)})}},{key:"_scheduleShow",value:function(a,b,c){var d=this;window.setTimeout(function(){return d._show(a,c)},b&&b.show||b||0)}},{key:"_scheduleHide",value:function(a,b,c,d){var e=this;window.setTimeout(function(){!1!==e._isOpen&&document.body.contains(e._tooltipNode)&&!("mouseleave"===d.type&&e._setTooltipNodeEvent(d,a,b,c))&&e._hide(a,c)},b&&b.hide||
b||0)}}]);return f}()});function onKeyPressUsuario(a){if(13==a)return document.getElementById("password").focus(),event.preventDefault(),!1}function onKeyPressPassword(a){if(13==a)return document.getElementById("captcha").focus(),event.preventDefault(),!1}function onKeyPressPassword2(a){if(13==a)return"none"!=window.getComputedStyle(document.getElementById("opTarjetaCoordenadas")).getPropertyValue("display")&&(document.getElementById("coordenada1").focus(),event.preventDefault()),!1}
function onKeyPressCaptcha(a){if(13==a)return"none"!=window.getComputedStyle(document.getElementById("opTarjetaCoordenadas")).getPropertyValue("display")&&(document.getElementById("coordenada1").focus(),event.preventDefault()),!1}function onKeyPressCaptcha2(a){if(13==a)return document.getElementById("usuario").focus(),event.preventDefault(),!1}
function onKeyPressCoordenada1(a){return 13==a?(document.getElementById("coordenada2").focus(),event.preventDefault(),!1):8==a?!0:/\\d/.test(String.fromCharCode(a))}function onKeyPressCoordenada2(a){return 13==a?(document.getElementById("login").click(),!1):8==a?!0:/\\d/.test(String.fromCharCode(a))}function onKeyPressPasswordA(a){if(13==a)return document.getElementById("password_n").focus(),event.preventDefault(),!1}
function onKeyPressPasswordN(a){if(13==a)return document.getElementById("password_n2").focus(),event.preventDefault(),!1}function onKeyPressPasswordN2(a){if(13==a)return document.getElementById("btnModificar").click(),event.preventDefault(),!1};function initialize(a,b,c,d,e,f,k){geocoder=new google.maps.Geocoder;map_s=new google.maps.Map(document.getElementById("map_canvas_s"),{zoom:8});icono="http://maps.google.com/mapfiles/ms/icons/red-dot.png";switch(c){case "M":icono="http://maps.google.com/mapfiles/ms/icons/green-dot.png";break;case "D":icono="http://maps.google.com/mapfiles/ms/icons/yellow-dot.png";break;case "P":icono="http://maps.google.com/mapfiles/ms/icons/blue-dot.png";break;case "4":icono="http://maps.google.com/mapfiles/ms/icons/purple-dot.png";
break;case "5":icono="http://maps.google.com/mapfiles/ms/icons/red-dot.png";break;default:icono="http://maps.google.com/mapfiles/ms/icons/red-dot.png"}codeAddress(a,map_s,b,icono,d,e,f,k);setTimeout(function(){var a=map_s.getCenter();google.maps.event.trigger(map_s,"resize");map_s.setCenter(a)},500)}
function initializeMapaCompleto(a,b){var c=new google.maps.LatLng(-35.039094,-64.126264),d={zoom:4,center:c},e=new google.maps.Map(document.getElementById("map-canvas"),d),d=puntos.length,f=0;(new google.maps.Geocoder).geocode({address:a},function(a,b){b==google.maps.GeocoderStatus.OK&&(c=a[0].geometry.location,e.setCenter(c))});for(f=0;f<d;f++){icono="http://maps.google.com/mapfiles/ms/icons/red-dot.png";switch(puntos[f][2]){case "M":icono="http://maps.google.com/mapfiles/ms/icons/green-dot.png";
break;case "D":icono="http://maps.google.com/mapfiles/ms/icons/yellow-dot.png";break;case "P":icono="http://maps.google.com/mapfiles/ms/icons/blue-dot.png";break;case "4":icono="http://maps.google.com/mapfiles/ms/icons/purple-dot.png";break;case "5":icono="http://maps.google.com/mapfiles/ms/icons/red-dot.png";break;default:icono="http://maps.google.com/mapfiles/ms/icons/red-dot.png"}codeAddressMultiple(puntos[f][0],e,puntos[f][1],icono,puntos[f][3],puntos[f][4],b,puntos[f][5])}setTimeout(function(){var a=
e.getCenter();google.maps.event.trigger(e,"resize");e.setCenter(a)},2E3)}function attachSecretMessage(a,b){var c=new google.maps.InfoWindow({content:b});google.maps.event.addListener(a,"click",function(){c.open(a.get("map"),a)})}
function codeAddress(a,b,c,d,e,f,k,l){2==k?(b.setCenter(new google.maps.LatLng(e,f)),e=new google.maps.Marker({map:b,position:new google.maps.LatLng(e,f),title:c,icon:d}),attachSecretMessage(e,"<b>Razon Social: </b>"+c+" <br /> <b>Direccion: </b>"+a+' <br /> <div style="text-align:center;"> <img src='+l+' alt="La imagen no esta disponible" style="max-width:640px;"> </div>')):geocoder.geocode({address:a},function(e,f){if(f==google.maps.GeocoderStatus.OK){b.setCenter(e[0].geometry.location);var h=new google.maps.Marker({map:b,
position:e[0].geometry.location,title:c,icon:d});attachSecretMessage(h,"<b>Razon Social: </b>"+c+" <br /> <b>Direccion: </b>"+a+' <br /> <div style="text-align:center;"> <img src='+l+' alt="La imagen no esta disponible" style="max-width:640px;"> </div>')}else alert("No se pudo instanciar geocoder por la siguiente razon: "+f)})}
function codeAddressMultiple(a,b,c,d,e,f,k,l){2==k?(e=new google.maps.Marker({map:b,position:new google.maps.LatLng(e,f),title:c,icon:d}),attachSecretMessage(e,"<b>Razon Social: </b>"+c+" <br /> <b>Direccion: </b>"+a+' <br /> <div style="text-align:center;"> <img src='+l+' alt="La imagen no esta disponible" style="max-width:640px;"> </div>')):(new google.maps.Geocoder).geocode({address:a},function(e,f){if(f==google.maps.GeocoderStatus.OK){var h=new google.maps.Marker({map:b,position:e[0].geometry.location,
title:c,icon:d});attachSecretMessage(h,"<b>Razon Social: </b>"+c+" <br /> <b>Direccion: </b>"+a+' <br /> <div style="text-align:center;"> <img src='+l+' alt="La imagen no esta disponible" style="max-width:640px;"> </div>')}})};PrimeFaces.widget.DataTable.prototype.toggleExpansion=function(){var a=PrimeFaces.widget.DataTable.prototype.toggleExpansion;return function(){var b=arguments[0].closest("tr");(expanded=b.hasClass("ui-expanded-row"))?b.next().remove():("single"===this.cfg.selectionMode&&this.unselectAllRows(),this.cfg.selectionMode&&this.selectRow(b,!1));return a.apply(this,arguments)}}();function keyupNroTarjeta(a){return 0==a.value.replaceAll(" ","").length?(blanquearDatosDeTarjeta(),!0):!1}function verificarLongitudBIN(a){return 8<a.length?(validarBIN(),!0):!1}function evaluarIngresoNroTarjeta(a,b){if(25<=b.value.length)return abrirLectorDeTarjeta(),b.value="",!1;if(13==a.keyCode&&0==b.value.length)return abrirLectorDeTarjeta(),!1;if(48>a.which||57<a.which)return!1};function mensajeriaConnect(){if("true"==debug)debugger;if(void 0==webSocketMensajeria||"undefined"===typeof webSocketMensajeria)webSocketMensajeria=new WebSocket(wsUriMSG),webSocketMensajeria.onerror=function(a){PEI_error_mensajeria(a)},webSocketMensajeria.onmessage=function(a){PEI_message_mensajeria(a)}}
function PEI_error_mensajeria(a){if("true"==debug)debugger;"undefined"!==typeof a.data&&writeToScreen('<span style="color: red;">ERROR:</span> '+a.data);if(void 0!=webSocketMensajeria||"undefined"!==typeof webSocketMensajeria)webSocketMensajeria.close(),webSocketMensajeria=void 0}
function PEI_message_mensajeria(a){if("true"==debug)debugger;a=JSON.parse(a.data);"MSG"==a.codigo?"C"==a.tipo?writeToScreenClear(a.mensaje):writeToScreen(a.mensaje):-2==a.codigo?writeToScreen(a.mensaje):writeToScreen("No se pudo interpretar la respuesta")};function Popup(a){var b=window.open("","my div","height=500,width=520,left=100,top=100,resizable=yes,scrollbars=yes,toolbar=no,status=no");b.document.write("<html><head><title>Ticket</title>");b.document.write('<link rel="stylesheet" href="styles/ticket-styles.css" type="text/css" />');b.document.write("</head><body >");b.document.write(a);b.document.write("</body></html>");b.document.close();myDelay=setInterval(function(){"complete"==b.document.readyState&&(clearInterval(myDelay),b.focus(),b.print(),
b.close())},10);return!0};var PublicidadFCNS={};ACGSiteScriptsFCNS.resultadoResize=function(){var a=$("#outputPanelProductos").height()-10;$("#panelPublicidad").height(a)};var PuntoDeVentaFCNS={cambiaFondoMsg:function(a,b,c,d,e){$("#"+a+" .ui-messages-info").css("color",b);$("#"+a+" .ui-messages-info").css("border-color",d);$("#"+a+" .ui-messages-info").css("background-color",c);$("#"+a+" .ui-messages-info-icon").attr("style","background: url("+e+".xhtml) no-repeat !important;");$("#"+a+" .ui-messages-info-icon").addClass("no-after");$("#"+a+" .ui-messages-info ui-corner-all").addClass("ui-messages");$("#"+a+" .ui-messages-info ui-corner-all").removeClass("ui-messages-error");
$("#"+a+" .ui-messages-error").css("color",b);$("#"+a+" .ui-messages-error").css("border-color",d);$("#"+a+" .ui-messages-error").css("background-color",c);$("#"+a+" .ui-messages-error-icon").attr("style","background: url("+e+".xhtml) no-repeat !important;");$("#"+a+" .ui-messages-error-icon").addClass("no-after");$("#"+a+" .ui-messages-error ui-corner-all").addClass("ui-messages");$("#"+a+" .ui-messages-error ui-corner-all").removeClass("ui-messages-error");$("#"+a+" .ui-messages-warn").css("color",
b);$("#"+a+" .ui-messages-warn").css("border-color",d);$("#"+a+" .ui-messages-warn").css("background-color",c);$("#"+a+" .ui-messages-warn-icon").attr("style","background: url("+e+".xhtml) no-repeat !important;");$("#"+a+" .ui-messages-warn-icon").addClass("no-after");$("#"+a+" .ui-messages-warn ui-corner-all").addClass("ui-messages");$("#"+a+" .ui-messages-warn ui-corner-all").removeClass("ui-messages-error");$("#"+a+" .ui-messages-fatal").css("color",b);$("#"+a+" .ui-messages-fatal").css("border-color",
d);$("#"+a+" .ui-messages-fatal").css("background-color",c);$("#"+a+" .ui-messages-fatal-icon").attr("style","background: url("+e+".xhtml) no-repeat !important;");$("#"+a+" .ui-messages-fatal-icon").addClass("no-after");$("#"+a+" .ui-messages-error ui-corner-all").addClass("ui-messages");$("#"+a+" .ui-messages-error ui-corner-all").removeClass("ui-messages-error")},monitorPVResize:function(){$("#headerPpal").outerHeight(!0);$("#footerPpal").outerHeight(!0);0<$("#panelProductos_header").length&&parseFloat($("#panelProductos_header").outerHeight(!0));
0<$("#panelProductos").length&&(parseFloat($("#panelProductos").css("padding-top").replace("px","")),parseFloat($("#panelProductos").css("padding-bottom").replace("px","")),parseFloat($("#panelProductos").css("border-top-width").replace("px","")),parseFloat($("#panelProductos").css("border-bottom-width").replace("px","")));0<$("#panelProductos_content").length&&(parseFloat($("#panelProductos_content").css("padding-top").replace("px","")),parseFloat($("#panelProductos_content").css("padding-bottom").replace("px",
"")),parseFloat($("#panelProductos_content").css("border-top-width").replace("px","")),parseFloat($("#panelProductos_content").css("border-bottom-width").replace("px","")));if(0<$("#tablaMonitorTRXSPV .ui-datatable-scrollable-body").length){var a=$("#outputPanelProductos").height()-($("#tablaMonitorTRXSPV .ui-datatable-header").outerHeight(!0)+$("#tablaMonitorTRXSPV .ui-datatable-scrollable-header").outerHeight(!0)+$("#tablaMonitorTRXSPV .ui-datatable-scrollable-footer-box").outerHeight(!0)+$("#tablaMonitorTRXSPV_paginator_bottom").outerHeight(!0)+
15);$("#tablaMonitorTRXSPV .ui-datatable-scrollable-body").attr("style","max-height: "+a+"px;");$("#tablaMonitorTRXSPV .ui-datatable-scrollable-body").attr("style","height: "+a+"px;")}},productoResize:function(){var a=window.innerHeight,a=a-$("#headerPpal").outerHeight(!0),a=a-$("#footerPpal").outerHeight(!0),a=a-(0<$("#msgsProductos").length?$("#msgsProductos").outerHeight(!0):0)-(0<$("#mnuIconos").length?$("#mnuIconos").outerHeight(!0):0)-((0<$("#panelProductos_header").length?parseFloat($("#panelProductos_header").outerHeight(!0)):
0)+(0<$("#panelProductos").length?parseFloat($("#panelProductos").css("padding-top").replace("px",""))+parseFloat($("#panelProductos").css("padding-bottom").replace("px",""))+parseFloat($("#panelProductos").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos").css("border-bottom-width").replace("px","")):0)+(0<$("#panelProductos_content").length?parseFloat($("#panelProductos_content").css("padding-top").replace("px",""))+parseFloat($("#panelProductos_content").css("padding-bottom").replace("px",
""))+parseFloat($("#panelProductos_content").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos_content").css("border-bottom-width").replace("px","")):0));$("#outputPanelProductos").height(a);PuntoDeVentaFCNS.resultadoResize()},puntoVentaResize:function(){var a=window.innerHeight;1024>window.innerWidth&&(a-=17);a-=$("#headerPpal").outerHeight(!0);a-=$("#footerPpal").outerHeight(!0);$("#bodyPpal").height(a-4)},cierraPanelProducto:function(){0<$("#panelProductos").length&&PF("panelProductosWV").close()},
refreshMonPV:function(){0<$("#panelGroupMonPV").length&&refreshMonProductosOnlinePV()},resultadoResize:function(){}};window.addEventListener("resize",PuntoDeVentaFCNS.puntoVentaResize);window.addEventListener("resize",PuntoDeVentaFCNS.productoResize);window.addEventListener("resize",PuntoDeVentaFCNS.monitorPVResize);$(document).ready(function(){PuntoDeVentaFCNS.puntoVentaResize();PuntoDeVentaFCNS.productoResize();PuntoDeVentaFCNS.monitorPVResize()});PuntoDeVentaFCNS.log=function(){};var ReportesBMRFCNS={};
ACGSiteScriptsFCNS.resultadoResize=function(){var a=window.innerHeight,a=a-$("#headerPpal").outerHeight(!0),a=a-$("#panelMnuIconos").outerHeight(!0),a=a-$("#footerPpal").outerHeight(!0),a=a-(0<$("#msgsProductos").length?$("#msgsProductos").outerHeight(!0):0)-((0<$("#panelProductos_header").length?parseFloat($("#panelProductos_header").outerHeight(!0)):0)+(0<$("#panelProductos").length?parseFloat($("#panelProductos").css("padding-top").replace("px",""))+parseFloat($("#panelProductos").css("padding-bottom").replace("px",""))+
parseFloat($("#panelProductos").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos").css("border-bottom-width").replace("px","")):0)+(0<$("#panelProductos_content").length?parseFloat($("#panelProductos_content").css("padding-top").replace("px",""))+parseFloat($("#panelProductos_content").css("padding-bottom").replace("px",""))+parseFloat($("#panelProductos_content").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos_content").css("border-bottom-width").replace("px",
"")):0));$("#outputPanelProductos").height(a);var a=$("#dataTableTabla .ui-datatable-header").outerHeight(!0),b=$("#dataTableTabla .ui-datatable-scrollable-header").outerHeight(!0),c=$("#dataTableTabla .ui-datatable-scrollable-footer").outerHeight(!0),d=$("#dataTableTabla .ui-datatable-footer").outerHeight(!0),e=$("#dataTableTabla_paginator_bottom").outerHeight(!0);0<$("#dataTableTabla .ui-datatable-scrollable-body").length&&(a=$("#outputPanelProductos").height()-$("#panelFiltro").height()-(("undefined"!==
typeof a?parseFloat(a):parseFloat("0"))+("undefined"!==typeof b?parseFloat(b):parseFloat("0"))+("undefined"!==typeof c?parseFloat(c):parseFloat("0"))+("undefined"!==typeof d?parseFloat(d):parseFloat("0"))+("undefined"!==typeof e?parseFloat(e):parseFloat("0"))+10)-(0<$("#botonesInferiores").length?$("#botonesInferiores").outerHeight(!0):0),$("#dataTableTabla .ui-datatable-scrollable-body").attr("style","max-height: "+a+"px;"),$("#dataTableTabla .ui-datatable-scrollable-body").attr("style","height: "+
a+"px;"))};var ReportesFCNS={};
ACGSiteScriptsFCNS.resultadoResize=function(){var a=window.innerHeight,a=a-$("#headerPpal").outerHeight(!0),a=a-(0<$("#panelMnuIconos").length?$("#panelMnuIconos").outerHeight(!0):0),a=a-$("#footerPpal").outerHeight(!0),a=a-(0<$("#msgsProductos").length?$("#msgsProductos").outerHeight(!0):0)-((0<$("#panelProductos_header").length?parseFloat($("#panelProductos_header").outerHeight(!0)):0)+(0<$("#panelProductos").length?parseFloat($("#panelProductos").css("padding-top").replace("px",""))+parseFloat($("#panelProductos").css("padding-bottom").replace("px",
""))+parseFloat($("#panelProductos").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos").css("border-bottom-width").replace("px","")):0)+(0<$("#panelProductos_content").length?parseFloat($("#panelProductos_content").css("padding-top").replace("px",""))+parseFloat($("#panelProductos_content").css("padding-bottom").replace("px",""))+parseFloat($("#panelProductos_content").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos_content").css("border-bottom-width").replace("px",
"")):0)),b=$("#panelSelUsr").outerHeight(!0),a=a-("undefined"!==typeof b?parseFloat(b):parseFloat("0"));$("#outputPanelProductos").height(a);var b=$("#dataTableTabla .ui-datatable-header").outerHeight(!0),c=$("#dataTableTabla .ui-datatable-scrollable-header").outerHeight(!0),d=$("#dataTableTabla .ui-datatable-scrollable-footer").outerHeight(!0),e=$("#dataTableTabla .ui-datatable-footer").outerHeight(!0),f=$("#dataTableTabla_paginator_bottom").outerHeight(!0);0<$("#dataTableTabla .ui-datatable-scrollable-body").length&&
(a=10,a=$("#outputPanelProductos").height()-$("#panelFiltro").height()-(("undefined"!==typeof b?parseFloat(b):parseFloat("0"))+("undefined"!==typeof c?parseFloat(c):parseFloat("0"))+("undefined"!==typeof d?parseFloat(d):parseFloat("0"))+("undefined"!==typeof e?parseFloat(e):parseFloat("0"))+("undefined"!==typeof f?parseFloat(f):parseFloat("0"))+parseFloat(a)),$("#dataTableTabla .ui-datatable-scrollable-body").attr("style","max-height: "+a+"px;"),$("#dataTableTabla .ui-datatable-scrollable-body").attr("style",
"height: "+a+"px;"));$("#dataTableTablaItems .ui-datatable-header").outerHeight(!0);b=$("#dataTableTablaItems .ui-datatable-scrollable-header").outerHeight(!0);c=$("#dataTableTablaItems .ui-datatable-scrollable-footer").outerHeight(!0);d=$("#dataTableTablaItems_paginator_bottom").outerHeight(!0);0<$("#dataTableTablaItems .ui-datatable-scrollable-body").length&&(a=10,a=$("#outputPanelProductos").height()-$("#panelFiltro").height()-(("undefined"!==typeof uiDataTableTablaItemsHeader?parseFloat(uiDataTableTablaItemsHeader):
parseFloat("0"))+("undefined"!==typeof b?parseFloat(b):parseFloat("0"))+("undefined"!==typeof c?parseFloat(c):parseFloat("0"))+("undefined"!==typeof uiDataTableTablaItemsTablaPaginatorBottom?parseFloat(d):parseFloat("0"))+parseFloat(a)+70),$("#dataTableTablaItems .ui-datatable-scrollable-body").attr("style","max-height: "+a+"px;"),$("#dataTableTablaItems .ui-datatable-scrollable-body").attr("style","height: "+a+"px;"));0<$("#dataTableTablaMap").length&&(a=10,a=$("#outputPanelProductos").height()-
$("#panelFiltro").height()-parseFloat(a),$("#dataTableTablaMap").attr("style","max-height: "+a+"px;"),$("#dataTableTablaMap").attr("style","height: "+a+"px;"))};var ResultadoBusquedaClienteFCNS={};
AdministracionFCNS.resultadoResize=function(){var a=window.innerHeight;$("#bodyPpal").width();1024>window.innerWidth&&(a-=17);a-=$("#headerPpal").outerHeight(!0);a-=$("#footerPpal").outerHeight(!0);a=a-4-parseFloat($("#bodyPpal").css("padding-top").replace("px",""));a-=parseFloat($("#bodyPpal").css("padding-bottom").replace("px",""));a-=parseFloat($("#bodyPpal").css("border-top").replace("px",""));a-=parseFloat($("#bodyPpal").css("border-bottom").replace("px",""));$("#bodyPpal").height(a);a-=$("#panelSelUsr_header").outerHeight(!0);
a-=$("#panelSelUsr_content").css("borderBottomWidth").replace("px","");a-=parseFloat($("#panelSelUsr_content").css("padding-top").replace("px",""));a-=parseFloat($("#panelSelUsr_content").css("padding-bottom").replace("px",""));$("#contSelUsr").css("maxHeight",a+"px");$("#contSelUsr").height(a);a-=10;$("#resuBusCliDT").css("maxHeight",a+"px");$("#resuBusCliDT").height(a)};$(window).on("resize",AdministracionFCNS.resultadoResize);$(document).ready(function(){AdministracionFCNS.resultadoResize()});function mensajeriaConnect(){if("true"==debug)debugger;if(void 0==webSocketMensajeria||"undefined"===typeof webSocketMensajeria)webSocketMensajeria=new WebSocket(wsUriMSG),webSocketMensajeria.onerror=function(a){SUBE_error_mensajeria(a)},webSocketMensajeria.onmessage=function(a){SUBE_message_mensajeria(a)}}
function SUBE_error_mensajeria(a){if("true"==debug)debugger;"undefined"!==typeof a.data&&writeToScreen('<span style="color: red;">ERROR:</span> '+a.data);if(void 0!=webSocketMensajeria||"undefined"!==typeof webSocketMensajeria)webSocketMensajeria.close(),webSocketMensajeria=void 0}
function SUBE_message_mensajeria(a){if("true"==debug)debugger;a=JSON.parse(a.data);"MSG"==a.codigo?"C"==a.tipo?writeToScreenClear(a.mensaje):writeToScreen(a.mensaje):-2==a.codigo?writeToScreen(a.mensaje):writeToScreen("No se pudo interpretar la respuesta")};var SuperPagoAgendaDestinatariosScriptsFCNS={};
ACGSiteScriptsFCNS.resultadoResize=function(){var a=window.innerHeight,a=a-$("#headerPpal").outerHeight(!0),a=a-(0<$("#panelMnuIconos").length?$("#panelMnuIconos").outerHeight(!0):0),a=a-$("#footerPpal").outerHeight(!0),a=a-(0<$("#msgsProductos").length?$("#msgsProductos").outerHeight(!0):0)-((0<$("#panelProductos_header").length?parseFloat($("#panelProductos_header").outerHeight(!0)):0)+(0<$("#panelProductos").length?parseFloat($("#panelProductos").css("padding-top").replace("px",""))+parseFloat($("#panelProductos").css("padding-bottom").replace("px",
""))+parseFloat($("#panelProductos").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos").css("border-bottom-width").replace("px","")):0)+(0<$("#panelProductos_content").length?parseFloat($("#panelProductos_content").css("padding-top").replace("px",""))+parseFloat($("#panelProductos_content").css("padding-bottom").replace("px",""))+parseFloat($("#panelProductos_content").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos_content").css("border-bottom-width").replace("px",
"")):0)),b=$("#panelSelUsr").outerHeight(!0),a=a-("undefined"!==typeof b?parseFloat(b):parseFloat("0"));$("#outputPanelProductos").height(a);var b=$("#agendaDestDT .ui-datatable-header").outerHeight(!0),c=$("#agendaDestDT .ui-datatable-scrollable-header").outerHeight(!0),d=$("#agendaDestDT .ui-datatable-scrollable-footer").outerHeight(!0),e=$("#agendaDestDT .ui-datatable-footer").outerHeight(!0),f=$("#agendaDestDT_paginator_bottom").outerHeight(!0);0<$("#agendaDestDT .ui-datatable-scrollable-body").length&&
(a=10,a=$("#outputPanelProductos").height()-$("#botoneraAgDest").outerHeight(!0)-(("undefined"!==typeof b?parseFloat(b):parseFloat("0"))+("undefined"!==typeof c?parseFloat(c):parseFloat("0"))+("undefined"!==typeof d?parseFloat(d):parseFloat("0"))+("undefined"!==typeof e?parseFloat(e):parseFloat("0"))+("undefined"!==typeof f?parseFloat(f):parseFloat("0"))+parseFloat(a)),$("#agendaDestDT .ui-datatable-scrollable-body").attr("style","max-height: "+a+"px;"),$("#agendaDestDT .ui-datatable-scrollable-body").attr("style",
"height: "+a+"px;"));$("#agendaDestDTItems .ui-datatable-header").outerHeight(!0);$("#agendaDestDTItems .ui-datatable-scrollable-header").outerHeight(!0);b=$("#agendaDestDTItems .ui-datatable-scrollable-footer").outerHeight(!0);$("#agendaDestDTItems_paginator_bottom").outerHeight(!0);0<$("#agendaDestDTItems .ui-datatable-scrollable-body").length&&(a=10,a=$("#outputPanelProductos").height()-$("#botoneraAgDest").outerHeight(!0)-(("undefined"!==typeof uiAgendaDestDTItemsHeader?parseFloat(uiAgendaDestDTItemsHeader):
parseFloat("0"))+("undefined"!==typeof uiAgendaDestDTItemsScrollableHeader?parseFloat(uiAgendaDestDTItemsScrollableHeader):parseFloat("0"))+("undefined"!==typeof b?parseFloat(b):parseFloat("0"))+("undefined"!==typeof uiAgendaDestDTItemsTablaPaginatorBottom?parseFloat(uiAgendaDestDTItemsPaginatorBottom):parseFloat("0"))+parseFloat(a)+70),$("#agendaDestDTItems .ui-datatable-scrollable-body").attr("style","max-height: "+a+"px;"),$("#agendaDestDTItems .ui-datatable-scrollable-body").attr("style","height: "+
a+"px;"));0<$("#agendaDestDTMap").length&&(a=10,a=$("#outputPanelProductos").height()-$("#botoneraAgDest").outerHeight(!0)-parseFloat(a),$("#agendaDestDTMap").attr("style","max-height: "+a+"px;"),$("#agendaDestDTMap").attr("style","height: "+a+"px;"))};var SuperPagoDepositoEnCuentaScriptsFCNS={};
ACGSiteScriptsFCNS.resultadoResize=function(){var a=window.innerHeight,a=a-$("#headerPpal").outerHeight(!0),a=a-(0<$("#panelMnuIconos").length?$("#panelMnuIconos").outerHeight(!0):0),a=a-$("#footerPpal").outerHeight(!0),a=a-(0<$("#msgsProductos").length?$("#msgsProductos").outerHeight(!0):0)-((0<$("#panelProductos_header").length?parseFloat($("#panelProductos_header").outerHeight(!0)):0)+(0<$("#panelProductos").length?parseFloat($("#panelProductos").css("padding-top").replace("px",""))+parseFloat($("#panelProductos").css("padding-bottom").replace("px",
""))+parseFloat($("#panelProductos").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos").css("border-bottom-width").replace("px","")):0)+(0<$("#panelProductos_content").length?parseFloat($("#panelProductos_content").css("padding-top").replace("px",""))+parseFloat($("#panelProductos_content").css("padding-bottom").replace("px",""))+parseFloat($("#panelProductos_content").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos_content").css("border-bottom-width").replace("px",
"")):0)),b=$("#panelSelUsr").outerHeight(!0),a=a-("undefined"!==typeof b?parseFloat(b):parseFloat("0"));$("#outputPanelProductos").height(a);var b=$("#depositosDT .ui-datatable-header").outerHeight(!0),c=$("#depositosDT .ui-datatable-scrollable-header").outerHeight(!0),d=$("#depositosDT .ui-datatable-scrollable-footer").outerHeight(!0),e=$("#depositosDT .ui-datatable-footer").outerHeight(!0),f=$("#depositosDT_paginator_bottom").outerHeight(!0);0<$("#depositosDT .ui-datatable-scrollable-body").length&&
(a=10,a=$("#outputPanelProductos").height()-$("#botoneraDepo").outerHeight(!0)-(0<$("#gridFiltroFecha").length?$("#gridFiltroFecha").outerHeight(!0):0)-(("undefined"!==typeof b?parseFloat(b):parseFloat("0"))+("undefined"!==typeof c?parseFloat(c):parseFloat("0"))+("undefined"!==typeof d?parseFloat(d):parseFloat("0"))+("undefined"!==typeof e?parseFloat(e):parseFloat("0"))+("undefined"!==typeof f?parseFloat(f):parseFloat("0"))+parseFloat(a)),$("#depositosDT .ui-datatable-scrollable-body").attr("style",
"max-height: "+a+"px;"),$("#depositosDT .ui-datatable-scrollable-body").attr("style","height: "+a+"px;"));$("#depositosDTItems .ui-datatable-header").outerHeight(!0);$("#depositosDTItems .ui-datatable-scrollable-header").outerHeight(!0);b=$("#depositosDTItems .ui-datatable-scrollable-footer").outerHeight(!0);$("#depositosDTItems_paginator_bottom").outerHeight(!0);0<$("#depositosDTItems .ui-datatable-scrollable-body").length&&(a=10,a=$("#outputPanelProductos").height()-$("#botoneraDepo").outerHeight(!0)-
(0<$("#gridFiltroFecha").length?$("#gridFiltroFecha").outerHeight(!0):0)-(("undefined"!==typeof uiAgendaDestDTItemsHeader?parseFloat(uiAgendaDestDTItemsHeader):parseFloat("0"))+("undefined"!==typeof uiAgendaDestDTItemsScrollableHeader?parseFloat(uiAgendaDestDTItemsScrollableHeader):parseFloat("0"))+("undefined"!==typeof b?parseFloat(b):parseFloat("0"))+("undefined"!==typeof uiAgendaDestDTItemsTablaPaginatorBottom?parseFloat(uiAgendaDestDTItemsPaginatorBottom):parseFloat("0"))+parseFloat(a)+70),$("#depositosDTItems .ui-datatable-scrollable-body").attr("style",
"max-height: "+a+"px;"),$("#depositosDTItems .ui-datatable-scrollable-body").attr("style","height: "+a+"px;"));0<$("#depositosDTMap").length&&(a=10,a=$("#outputPanelProductos").height()-$("#botoneraDepo").outerHeight(!0)-parseFloat(a),$("#depositosDTMap").attr("style","max-height: "+a+"px;"),$("#depositosDTMap").attr("style","height: "+a+"px;"))};var SuperPagoMovimientoDeCuentaScriptsFCNS={};
ACGSiteScriptsFCNS.resultadoResize=function(){var a=window.innerHeight,a=a-$("#headerPpal").outerHeight(!0),a=a-(0<$("#panelMnuIconos").length?$("#panelMnuIconos").outerHeight(!0):0),a=a-$("#footerPpal").outerHeight(!0),a=a-(0<$("#msgsProductos").length?$("#msgsProductos").outerHeight(!0):0)-((0<$("#panelProductos_header").length?parseFloat($("#panelProductos_header").outerHeight(!0)):0)+(0<$("#panelProductos").length?parseFloat($("#panelProductos").css("padding-top").replace("px",""))+parseFloat($("#panelProductos").css("padding-bottom").replace("px",
""))+parseFloat($("#panelProductos").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos").css("border-bottom-width").replace("px","")):0)+(0<$("#panelProductos_content").length?parseFloat($("#panelProductos_content").css("padding-top").replace("px",""))+parseFloat($("#panelProductos_content").css("padding-bottom").replace("px",""))+parseFloat($("#panelProductos_content").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos_content").css("border-bottom-width").replace("px",
"")):0)),b=$("#panelSelUsr").outerHeight(!0),a=a-("undefined"!==typeof b?parseFloat(b):parseFloat("0"));$("#outputPanelProductos").height(a);var b=$("#movimientosDT .ui-datatable-header").outerHeight(!0),c=$("#movimientosDT .ui-datatable-scrollable-header").outerHeight(!0),d=$("#movimientosDT .ui-datatable-scrollable-footer").outerHeight(!0),e=$("#movimientosDT .ui-datatable-footer").outerHeight(!0),f=$("#movimientosDT_paginator_bottom").outerHeight(!0);0<$("#movimientosDT .ui-datatable-scrollable-body").length&&
(a=10,a=$("#outputPanelProductos").height()-$("#panelFiltro").height()-(0<$("#gridFiltroFecha").length?$("#gridFiltroFecha").outerHeight(!0):0)-(("undefined"!==typeof b?parseFloat(b):parseFloat("0"))+("undefined"!==typeof c?parseFloat(c):parseFloat("0"))+("undefined"!==typeof d?parseFloat(d):parseFloat("0"))+("undefined"!==typeof e?parseFloat(e):parseFloat("0"))+("undefined"!==typeof f?parseFloat(f):parseFloat("0"))+parseFloat(a)),$("#movimientosDT .ui-datatable-scrollable-body").attr("style","max-height: "+
a+"px;"),$("#movimientosDT .ui-datatable-scrollable-body").attr("style","height: "+a+"px;"));$("#movimientosDTItems .ui-datatable-header").outerHeight(!0);$("#movimientosDTItems .ui-datatable-scrollable-header").outerHeight(!0);b=$("#movimientosDTItems .ui-datatable-scrollable-footer").outerHeight(!0);$("#movimientosDTItems_paginator_bottom").outerHeight(!0);0<$("#movimientosDTItems .ui-datatable-scrollable-body").length&&(a=10,a=$("#outputPanelProductos").height()-$("#panelFiltro").height()-(0<$("#gridFiltroFecha").length?
$("#gridFiltroFecha").outerHeight(!0):0)-(("undefined"!==typeof uiAgendaDestDTItemsHeader?parseFloat(uiAgendaDestDTItemsHeader):parseFloat("0"))+("undefined"!==typeof uiAgendaDestDTItemsScrollableHeader?parseFloat(uiAgendaDestDTItemsScrollableHeader):parseFloat("0"))+("undefined"!==typeof b?parseFloat(b):parseFloat("0"))+("undefined"!==typeof uiAgendaDestDTItemsTablaPaginatorBottom?parseFloat(uiAgendaDestDTItemsPaginatorBottom):parseFloat("0"))+parseFloat(a)+70),$("#movimientosDTItems .ui-datatable-scrollable-body").attr("style",
"max-height: "+a+"px;"),$("#movimientosDTItems .ui-datatable-scrollable-body").attr("style","height: "+a+"px;"));0<$("#movimientosDTMap").length&&(a=10,a=$("#outputPanelProductos").height()-$("#botoneraTrfs").outerHeight(!0)-parseFloat(a),$("#movimientosDTMap").attr("style","max-height: "+a+"px;"),$("#movimientosDTMap").attr("style","height: "+a+"px;"))};var SuperPagoSolicitudDeDineroScriptsFCNS={};
ACGSiteScriptsFCNS.resultadoResize=function(){var a=window.innerHeight,a=a-$("#headerPpal").outerHeight(!0),a=a-(0<$("#panelMnuIconos").length?$("#panelMnuIconos").outerHeight(!0):0),a=a-$("#footerPpal").outerHeight(!0),a=a-(0<$("#msgsProductos").length?$("#msgsProductos").outerHeight(!0):0)-((0<$("#panelProductos_header").length?parseFloat($("#panelProductos_header").outerHeight(!0)):0)+(0<$("#panelProductos").length?parseFloat($("#panelProductos").css("padding-top").replace("px",""))+parseFloat($("#panelProductos").css("padding-bottom").replace("px",
""))+parseFloat($("#panelProductos").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos").css("border-bottom-width").replace("px","")):0)+(0<$("#panelProductos_content").length?parseFloat($("#panelProductos_content").css("padding-top").replace("px",""))+parseFloat($("#panelProductos_content").css("padding-bottom").replace("px",""))+parseFloat($("#panelProductos_content").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos_content").css("border-bottom-width").replace("px",
"")):0)),b=$("#panelSelUsr").outerHeight(!0),a=a-("undefined"!==typeof b?parseFloat(b):parseFloat("0"));$("#outputPanelProductos").height(a);var b=$("#solicitudesDeDineroDT .ui-datatable-header").outerHeight(!0),c=$("#solicitudesDeDineroDT .ui-datatable-scrollable-header").outerHeight(!0),d=$("#solicitudesDeDineroDT .ui-datatable-scrollable-footer").outerHeight(!0),e=$("#solicitudesDeDineroDT .ui-datatable-footer").outerHeight(!0),f=$("#solicitudesDeDineroDT_paginator_bottom").outerHeight(!0);0<$("#solicitudesDeDineroDT .ui-datatable-scrollable-body").length&&
(a=10,a=$("#outputPanelProductos").height()-$("#botoneraSolDin").outerHeight(!0)-(0<$("#gridFiltroFecha").length?$("#gridFiltroFecha").outerHeight(!0):0)-(("undefined"!==typeof b?parseFloat(b):parseFloat("0"))+("undefined"!==typeof c?parseFloat(c):parseFloat("0"))+("undefined"!==typeof d?parseFloat(d):parseFloat("0"))+("undefined"!==typeof e?parseFloat(e):parseFloat("0"))+("undefined"!==typeof f?parseFloat(f):parseFloat("0"))+parseFloat(a)),$("#solicitudesDeDineroDT .ui-datatable-scrollable-body").attr("style",
"max-height: "+a+"px;"),$("#solicitudesDeDineroDT .ui-datatable-scrollable-body").attr("style","height: "+a+"px;"));$("#solicitudesDeDineroDTItems .ui-datatable-header").outerHeight(!0);$("#solicitudesDeDineroDTItems .ui-datatable-scrollable-header").outerHeight(!0);b=$("#solicitudesDeDineroDTItems .ui-datatable-scrollable-footer").outerHeight(!0);$("#solicitudesDeDineroDTItems_paginator_bottom").outerHeight(!0);0<$("#solicitudesDeDineroDTItems .ui-datatable-scrollable-body").length&&(a=10,a=$("#outputPanelProductos").height()-
$("#botoneraSolDin").outerHeight(!0)-(0<$("#gridFiltroFecha").length?$("#gridFiltroFecha").outerHeight(!0):0)-(("undefined"!==typeof uiAgendaDestDTItemsHeader?parseFloat(uiAgendaDestDTItemsHeader):parseFloat("0"))+("undefined"!==typeof uiAgendaDestDTItemsScrollableHeader?parseFloat(uiAgendaDestDTItemsScrollableHeader):parseFloat("0"))+("undefined"!==typeof b?parseFloat(b):parseFloat("0"))+("undefined"!==typeof uiAgendaDestDTItemsTablaPaginatorBottom?parseFloat(uiAgendaDestDTItemsPaginatorBottom):
parseFloat("0"))+parseFloat(a)+70),$("#solicitudesDeDineroDTItems .ui-datatable-scrollable-body").attr("style","max-height: "+a+"px;"),$("#solicitudesDeDineroDTItems .ui-datatable-scrollable-body").attr("style","height: "+a+"px;"));0<$("#solicitudesDeDineroDTMap").length&&(a=10,a=$("#outputPanelProductos").height()-$("#botoneraSolDin").outerHeight(!0)-parseFloat(a),$("#solicitudesDeDineroDTMap").attr("style","max-height: "+a+"px;"),$("#solicitudesDeDineroDTMap").attr("style","height: "+a+"px;"))};var SuperPagoTransferenciasScriptsFCNS={};
ACGSiteScriptsFCNS.resultadoResize=function(){var a=window.innerHeight,a=a-$("#headerPpal").outerHeight(!0),a=a-(0<$("#panelMnuIconos").length?$("#panelMnuIconos").outerHeight(!0):0),a=a-$("#footerPpal").outerHeight(!0),a=a-(0<$("#msgsProductos").length?$("#msgsProductos").outerHeight(!0):0)-((0<$("#panelProductos_header").length?parseFloat($("#panelProductos_header").outerHeight(!0)):0)+(0<$("#panelProductos").length?parseFloat($("#panelProductos").css("padding-top").replace("px",""))+parseFloat($("#panelProductos").css("padding-bottom").replace("px",
""))+parseFloat($("#panelProductos").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos").css("border-bottom-width").replace("px","")):0)+(0<$("#panelProductos_content").length?parseFloat($("#panelProductos_content").css("padding-top").replace("px",""))+parseFloat($("#panelProductos_content").css("padding-bottom").replace("px",""))+parseFloat($("#panelProductos_content").css("border-top-width").replace("px",""))+parseFloat($("#panelProductos_content").css("border-bottom-width").replace("px",
"")):0)),b=$("#panelSelUsr").outerHeight(!0),a=a-("undefined"!==typeof b?parseFloat(b):parseFloat("0"));$("#outputPanelProductos").height(a);var b=$("#transfersDT .ui-datatable-header").outerHeight(!0),c=$("#transfersDT .ui-datatable-scrollable-header").outerHeight(!0),d=$("#transfersDT .ui-datatable-scrollable-footer").outerHeight(!0),e=$("#transfersDT .ui-datatable-footer").outerHeight(!0),f=$("#transfersDT_paginator_bottom").outerHeight(!0);0<$("#transfersDT .ui-datatable-scrollable-body").length&&
(a=10,a=$("#outputPanelProductos").height()-$("#botoneraTrfs").outerHeight(!0)-(0<$("#gridFiltroFecha").length?$("#gridFiltroFecha").outerHeight(!0):0)-(("undefined"!==typeof b?parseFloat(b):parseFloat("0"))+("undefined"!==typeof c?parseFloat(c):parseFloat("0"))+("undefined"!==typeof d?parseFloat(d):parseFloat("0"))+("undefined"!==typeof e?parseFloat(e):parseFloat("0"))+("undefined"!==typeof f?parseFloat(f):parseFloat("0"))+parseFloat(a)),$("#transfersDT .ui-datatable-scrollable-body").attr("style",
"max-height: "+a+"px;"),$("#transfersDT .ui-datatable-scrollable-body").attr("style","height: "+a+"px;"));$("#transfersDTItems .ui-datatable-header").outerHeight(!0);$("#transfersDTItems .ui-datatable-scrollable-header").outerHeight(!0);b=$("#transfersDTItems .ui-datatable-scrollable-footer").outerHeight(!0);$("#transfersDTItems_paginator_bottom").outerHeight(!0);0<$("#transfersDTItems .ui-datatable-scrollable-body").length&&(a=10,a=$("#outputPanelProductos").height()-$("#botoneraTrfs").outerHeight(!0)-
(0<$("#gridFiltroFecha").length?$("#gridFiltroFecha").outerHeight(!0):0)-(("undefined"!==typeof uiAgendaDestDTItemsHeader?parseFloat(uiAgendaDestDTItemsHeader):parseFloat("0"))+("undefined"!==typeof uiAgendaDestDTItemsScrollableHeader?parseFloat(uiAgendaDestDTItemsScrollableHeader):parseFloat("0"))+("undefined"!==typeof b?parseFloat(b):parseFloat("0"))+("undefined"!==typeof uiAgendaDestDTItemsTablaPaginatorBottom?parseFloat(uiAgendaDestDTItemsPaginatorBottom):parseFloat("0"))+parseFloat(a)+70),$("#transfersDTItems .ui-datatable-scrollable-body").attr("style",
"max-height: "+a+"px;"),$("#transfersDTItems .ui-datatable-scrollable-body").attr("style","height: "+a+"px;"));0<$("#transfersDTMap").length&&(a=10,a=$("#outputPanelProductos").height()-$("#botoneraTrfs").outerHeight(!0)-parseFloat(a),$("#transfersDTMap").attr("style","max-height: "+a+"px;"),$("#transfersDTMap").attr("style","height: "+a+"px;"))};