package com.americacg.cargavirtual.core.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2020-03-02T12:04:43.374-03:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.core.cargavirtual.americacg.com", name = "CoreServicePortType")
@XmlSeeAlso({com.americacg.cargavirtual.core.model.ObjectFactory.class, ObjectFactory.class})
public interface CoreServicePortType {

    @WebMethod
    @RequestWrapper(localName = "ajustarTransaccion", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.AjustarTransaccion")
    @ResponseWrapper(localName = "ajustarTransaccionResponse", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.AjustarTransaccionResponse")
    @WebResult(name = "out", targetNamespace = "http://service.core.cargavirtual.americacg.com")
    public com.americacg.cargavirtual.core.model.Ticket ajustarTransaccion(
        @WebParam(name = "in0", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        javax.xml.datatype.XMLGregorianCalendar in1,
        @WebParam(name = "in2", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in2,
        @WebParam(name = "in3", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in3,
        @WebParam(name = "in4", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Float in4,
        @WebParam(name = "in5", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Float in5,
        @WebParam(name = "in6", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in6
    );

    @WebMethod
    @RequestWrapper(localName = "prueba", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.Prueba")
    @ResponseWrapper(localName = "pruebaResponse", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.PruebaResponse")
    @WebResult(name = "out", targetNamespace = "http://service.core.cargavirtual.americacg.com")
    public com.americacg.cargavirtual.core.model.Prueba prueba(
        @WebParam(name = "in0", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in0
    );

    @WebMethod
    @RequestWrapper(localName = "enviarConfirmacion", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.EnviarConfirmacion")
    @ResponseWrapper(localName = "enviarConfirmacionResponse", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.EnviarConfirmacionResponse")
    @WebResult(name = "out", targetNamespace = "http://service.core.cargavirtual.americacg.com")
    public java.lang.Boolean enviarConfirmacion(
        @WebParam(name = "in0", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in1,
        @WebParam(name = "in2", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in2,
        @WebParam(name = "in3", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        javax.xml.datatype.XMLGregorianCalendar in4,
        @WebParam(name = "in5", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        javax.xml.datatype.XMLGregorianCalendar in5,
        @WebParam(name = "in6", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in6,
        @WebParam(name = "in7", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in7,
        @WebParam(name = "in8", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Float in8,
        @WebParam(name = "in9", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Integer in9,
        @WebParam(name = "in10", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Integer in10,
        @WebParam(name = "in11", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in11
    );

    @WebMethod
    @RequestWrapper(localName = "estadoCore", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.EstadoCore")
    @ResponseWrapper(localName = "estadoCoreResponse", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.EstadoCoreResponse")
    @WebResult(name = "out", targetNamespace = "http://service.core.cargavirtual.americacg.com")
    public com.americacg.cargavirtual.core.model.ArrayOfEstado estadoCore(
        @WebParam(name = "in0", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in1
    );

    @WebMethod
    @RequestWrapper(localName = "apagar", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.Apagar")
    @ResponseWrapper(localName = "apagarResponse", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.ApagarResponse")
    @WebResult(name = "out", targetNamespace = "http://service.core.cargavirtual.americacg.com")
    public com.americacg.cargavirtual.core.model.RespApagado apagar(
        @WebParam(name = "in0", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in2
    );

    @WebMethod
    @RequestWrapper(localName = "realizarVenta", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.RealizarVenta")
    @ResponseWrapper(localName = "realizarVentaResponse", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.RealizarVentaResponse")
    @WebResult(name = "out", targetNamespace = "http://service.core.cargavirtual.americacg.com")
    public com.americacg.cargavirtual.core.model.Ticket realizarVenta(
        @WebParam(name = "in0", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in1,
        @WebParam(name = "in2", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        javax.xml.datatype.XMLGregorianCalendar in4,
        @WebParam(name = "in5", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in5,
        @WebParam(name = "in6", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in6,
        @WebParam(name = "in7", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Float in7,
        @WebParam(name = "in8", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Integer in8,
        @WebParam(name = "in9", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Integer in9,
        @WebParam(name = "in10", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in10,
        @WebParam(name = "in11", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in11,
        @WebParam(name = "in12", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in12
    );

    @WebMethod
    @RequestWrapper(localName = "consultarSaldo", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.ConsultarSaldo")
    @ResponseWrapper(localName = "consultarSaldoResponse", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.ConsultarSaldoResponse")
    @WebResult(name = "out", targetNamespace = "http://service.core.cargavirtual.americacg.com")
    public com.americacg.cargavirtual.core.model.Ticket consultarSaldo(
        @WebParam(name = "in0", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in1,
        @WebParam(name = "in2", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in2,
        @WebParam(name = "in3", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        javax.xml.datatype.XMLGregorianCalendar in4,
        @WebParam(name = "in5", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in5,
        @WebParam(name = "in6", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in6,
        @WebParam(name = "in7", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in7,
        @WebParam(name = "in8", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in8
    );

    @WebMethod
    @RequestWrapper(localName = "anularTransaccion", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.AnularTransaccion")
    @ResponseWrapper(localName = "anularTransaccionResponse", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.AnularTransaccionResponse")
    @WebResult(name = "out", targetNamespace = "http://service.core.cargavirtual.americacg.com")
    public com.americacg.cargavirtual.core.model.Ticket anularTransaccion(
        @WebParam(name = "in0", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in1,
        @WebParam(name = "in2", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in2,
        @WebParam(name = "in3", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        javax.xml.datatype.XMLGregorianCalendar in4,
        @WebParam(name = "in5", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in5,
        @WebParam(name = "in6", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in6,
        @WebParam(name = "in7", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in7,
        @WebParam(name = "in8", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Float in8,
        @WebParam(name = "in9", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Integer in9,
        @WebParam(name = "in10", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Integer in10
    );

    @WebMethod
    @RequestWrapper(localName = "resetearHashConectores", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.ResetearHashConectores")
    @ResponseWrapper(localName = "resetearHashConectoresResponse", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.ResetearHashConectoresResponse")
    @WebResult(name = "out", targetNamespace = "http://service.core.cargavirtual.americacg.com")
    public java.lang.String resetearHashConectores(
        @WebParam(name = "in0", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in1
    );

    @WebMethod
    @RequestWrapper(localName = "consultarTransaccion", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.ConsultarTransaccion")
    @ResponseWrapper(localName = "consultarTransaccionResponse", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.ConsultarTransaccionResponse")
    @WebResult(name = "out", targetNamespace = "http://service.core.cargavirtual.americacg.com")
    public com.americacg.cargavirtual.core.model.Ticket consultarTransaccion(
        @WebParam(name = "in0", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in0,
        @WebParam(name = "in1", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in1,
        @WebParam(name = "in2", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in2,
        @WebParam(name = "in3", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        javax.xml.datatype.XMLGregorianCalendar in4,
        @WebParam(name = "in5", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in5,
        @WebParam(name = "in6", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in6,
        @WebParam(name = "in7", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Long in7,
        @WebParam(name = "in8", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Float in8,
        @WebParam(name = "in9", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Integer in9,
        @WebParam(name = "in10", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Integer in10,
        @WebParam(name = "in11", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in11,
        @WebParam(name = "in12", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in12,
        @WebParam(name = "in13", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.Boolean in13
    );

    @WebMethod
    @RequestWrapper(localName = "activar", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.Activar")
    @ResponseWrapper(localName = "activarResponse", targetNamespace = "http://service.core.cargavirtual.americacg.com", className = "com.americacg.cargavirtual.core.service.ActivarResponse")
    @WebResult(name = "out", targetNamespace = "http://service.core.cargavirtual.americacg.com")
    public com.americacg.cargavirtual.core.model.RespApagado activar(
        @WebParam(name = "in0", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://service.core.cargavirtual.americacg.com")
        java.lang.String in2
    );
}
